#if os(macOS) || os(Linux)

  import Foundation
  import XCTest

  import SourceControl
  @testable import SwiftAtprotoLex

  final class PluginSourceBranchingTests: XCTestCase {
    private func makeTempDir() throws -> URL {
      let url = FileManager.default.temporaryDirectory.appending(component: "swift-atproto-tests-\(UUID().uuidString)")
      try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
      return url
    }

    private func runWriteSchemaCode(to baseURL: URL, generate: GenerateOption, pluginSource: PluginSource) async throws {
      try await writeSchemaCode(
        for: [:],
        with: [:],
        to: baseURL,
        generate: generate,
        pluginSource: pluginSource
      )
    }

    private func generatedProvenanceMarker() -> String { "Generated by swift-atproto" }

    func testBuildModeWithoutServerWritesHeaderOnlyPlaceholder() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertTrue(contents.contains("DO NOT EDIT"))
      XCTAssertTrue(contents.contains(generatedProvenanceMarker()))
    }

    func testBuildModeWithServerWritesGeneratedProtocol() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .build)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertTrue(contents.contains(generatedProvenanceMarker()))
    }

    func testCommandModeWithServerWritesGeneratedProtocol() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .command)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertTrue(contents.contains(generatedProvenanceMarker()))
    }

    func testCommandModeWithoutServerSkipsWriteWhenNoFile() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .command)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertFalse(FileManager.default.fileExists(atPath: serverURL.path))
    }

    func testCommandModeWithoutServerRemovesAnyExistingFile() async throws {
      let cases: [(label: String, contents: Data)] = [
        ("zero-byte placeholder from older swift-atproto", Data()),
        ("stale generated server protocol", Data("//\n// DO NOT EDIT\n//\n// Generated by swift-atproto\n//\nimport OpenAPIRuntime\n".utf8)),
        ("anything else at the path", Data("// any content at this swift-atproto-owned filename is dropped\n".utf8)),
      ]
      for (label, payload) in cases {
        let tmp = try makeTempDir()
        defer { try? FileManager.default.removeItem(at: tmp) }
        let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
        try payload.write(to: serverURL)
        try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .command)
        XCTAssertFalse(FileManager.default.fileExists(atPath: serverURL.path), "command mode must remove \(label)")
      }
    }

    func testBuildModeOverwritesPreExistingContent() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      let priorContent = "// stale content from a prior server-on run\n"
      try priorContent.write(to: serverURL, atomically: true, encoding: .utf8)
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertNotEqual(contents, priorContent, "build mode placeholder must overwrite stale content")
      XCTAssertTrue(contents.contains(generatedProvenanceMarker()))
    }

    func testServerOnThenOffSequenceUnderBuild() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .build)
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path), "build mode must keep the file present as a placeholder")
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertFalse(contents.contains("XRPCAPIProtocol"), "post-toggle placeholder must not retain server-mode declarations")
    }

    func testServerOnThenOffSequenceUnderCommand() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .command)
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .command)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertFalse(FileManager.default.fileExists(atPath: serverURL.path), "command mode must remove the stale generated file when server is dropped")
    }

    func testBuildThenCommandThenBuildSequence() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path), "build placeholder created on first run")
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .command)
      XCTAssertFalse(FileManager.default.fileExists(atPath: serverURL.path), "command mode cleans up build-plugin placeholder")
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path), "build mode restores the placeholder")
    }

    func testCommandModeServerOnlyDoesNotThrow() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: .server, pluginSource: .command)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      let clientURL = tmp.appending(component: "XRPCAPIClient.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      XCTAssertTrue(FileManager.default.fileExists(atPath: clientURL.path))
      let serverContents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertTrue(serverContents.contains(generatedProvenanceMarker()))
      let clientContents = try String(contentsOf: clientURL, encoding: .utf8)
      XCTAssertTrue(clientContents.contains("DO NOT EDIT"), "XRPCAPIClient.swift must still carry the standard header")
    }

    func testBuildServerOnThenCommandServerOff() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .build)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .command)
      XCTAssertFalse(FileManager.default.fileExists(atPath: serverURL.path), "command mode must remove the file produced by a prior build-mode .server run")
    }

    func testCommandServerOnThenBuildServerOff() async throws {
      let tmp = try makeTempDir()
      defer { try? FileManager.default.removeItem(at: tmp) }
      try await runWriteSchemaCode(to: tmp, generate: [.client, .server], pluginSource: .command)
      let serverURL = tmp.appending(component: "XRPCAPIProtocol.swift")
      XCTAssertTrue(FileManager.default.fileExists(atPath: serverURL.path))
      try await runWriteSchemaCode(to: tmp, generate: .client, pluginSource: .build)
      let contents = try String(contentsOf: serverURL, encoding: .utf8)
      XCTAssertFalse(contents.contains("XRPCAPIProtocol"), "build placeholder must overwrite the prior command-mode protocol declaration")
      XCTAssertTrue(contents.contains(generatedProvenanceMarker()))
    }
  }

#endif
